# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mitchelpl
          template: classic
          base: ""
          config_display: large
          config_timezone: Europe/Warsaw
          plugin_achievements: yes
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_contributors: yes
          plugin_contributors_categories: {
            "📚 Documentation": ["README.md", "docs/**"],
            "💻 Code": ["source/**", "src/**"],
            "#️⃣ Others": ["*"]
          }
          plugin_contributors_contributions: yes
          plugin_contributors_head: master
          plugin_contributors_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_contributors_sections: contributors
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_licenses_ratio: yes
          plugin_people: yes
          plugin_people_limit: 30
          plugin_people_shuffle: yes
          plugin_people_size: 24
          plugin_people_thanks: Sheepposu, jedenastka
          plugin_people_types: followers, following
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_traffic: yes
          repositories_forks: yes		  
#		  extras_css: |
#			  div.field { color: white !important; }
#			  h2.field { color: white !important; }