# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: More-Stats-Light
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: 'more_stats_light.svg'
          user: mitchelpl
          template: classic
          config_gemoji: yes
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          base: ""
          extras_css: |
            h2:first-of-type, h2.field:first-of-type { 
              margin-top: 15px !important;
            }
            *, div, div.field { 
              color: #000000FF !important;
              background-color: #FFFFFFFF !important;
              font-size: 15px !important;
            }
            h2, h2.field { 
              color: #000000FF !important;
              background-color: #FFFFFFFF !important;
              font-weight: bold !important;
              font-size: 20px !important;
              margin-bottom: 15px !important;
              margin-top: 50px !important;
            }
          config_display: large
          config_timezone: Europe/Warsaw
          plugin_achievements: yes
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 4
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_thanks: Sheepposu, jedenastka
          plugin_people_types: followers, following, thanks
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          repositories_forks: no
          config_order: wakatime, activity, people, achievements